import { v4 as uuidv4 } from "uuid";

export const productGridDummyData = [
  {
    id: uuidv4(),
    name: "Meditation Bowl",
    image: "/images/p1-min.png",
    price: "2900",
    category: "collection" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Leather Tote Bag",
    image: "/images/p2-min.png",
    price: "2900",
    category: "collection" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Water Offering Vessel",
    image: "/images/p3-min.png",
    price: "2900",
    category: "collection" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Silver Moon Perfume",
    image: "/images/p4-min.png",
    price: "2900",
    category: "collection" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Chinese Style Porcelain Bowl",
    image: "/images/p5-min.png",
    price: "2900",
    category: "collection" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Pashmina Scarf",
    image: "/images/p6-min.png",
    price: "2900",
    category: "collection" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "8 Lucky Sign Keychain",
    image: "/images/p7-min.png",
    price: "2900",
    category: "collection" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Incense Burner",
    image: "/images/p8-min.png",
    price: "2900",
    category: "collection" as const,
    quantity: 1,
  },
];

export const favoriteGridDummyData = [
  {
    id: uuidv4(),
    name: "Bracelets",
    image: "/images/pf1-min.png",
    price: "2900",
    category: "favorite" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Tote Bags",
    image: "/images/pf3-min.png",
    price: "290",
    category: "favorite" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Prayer Flags",
    image: "/images/pf2-min.png",
    price: "290",
    category: "favorite" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Wall Prayer Wheel",
    image: "/images/pf4-min.png",
    price: "900",
    category: "favorite" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Bracelets",
    image: "/images/pf1-min.png",
    price: "2900",
    category: "favorite" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Tote Bags",
    image: "/images/pf3-min.png",
    price: "290",
    category: "favorite" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Prayer Flags",
    image: "/images/pf2-min.png",
    price: "290",
    category: "favorite" as const,
    quantity: 1,
  },
  {
    id: uuidv4(),
    name: "Wall Prayer Wheel",
    image: "/images/pf4-min.png",
    price: "900",
    category: "favorite" as const,
    quantity: 1,
  },
];

export const adminProductList = [
  {
    productId : uuidv4(),
    image : '/images/p1-min.png', 
    name : 'Meditation Bowl', 
    category : 'collection', 
    price : 2900,
  },
  {
    productId : uuidv4(),
    image : '/images/p2-min.png', 
    name : 'Leather Tote Bag', 
    category : 'collection', 
    price : 290,
  },
  {
    productId : uuidv4(),
    image : '/images/p3-min.png', 
    name : 'Water offering vesel', 
    category : 'collection', 
    price : 3900,
  },
  {
    productId : uuidv4(),
    image : '/images/p4-min.png', 
    name : 'Silver Moon perfume', 
    category : 'collection', 
    price : 900,
  },
]