import type { Metadata } from "next";
import "./globals.css";
import CartContext from "./context/CartContext";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Nubra Souvenir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Toaster position="top-center" reverseOrder={false} />
        <CartContext>{children}</CartContext>
        <Footer />
      </body>
    </html>
  );
}
