import type { Metadata } from "next";
import "./globals.css";
import CartContext from "./context/CartContext";
import ProductContext from "./context/ProductContext";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
import { Lora } from "next/font/google";

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
  display: 'swap',
  variable: '--font-lora',
});

export const metadata: Metadata = {
  title: "Nubra Souvenir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased ${lora.variable}`}>
          <Toaster position="top-center" reverseOrder={false} />
          <ProductContext>
            <CartContext>{children}</CartContext>
          </ProductContext>
        </body>
      </html>
    </ClerkProvider>
  );
}
